- hosts: routers
  gather_facts: false
  roles:
    - { role: router_base,    tag: [ 'rbase'] }

- hosts: webservers
  gather_facts: true
  become: true
  roles:
    - { role: base_packages_linux,  tag:  [ 'bpack'] }
    - { role: apache2_linux,        tag: [ 'apache2']}
  


